### ISSUE TITLE
containers content is not scrollable with response design

### ISSUE THREAD

**Issue by danchdanchdanch** [BcRikko/NES.css#18]
Containers content is not scrollable with response design
May be try something like `overflow: scroll` ? 

![2018-11-29 11 41 06](https://user-images.githubusercontent.com/5562992/49209491-ae1f5600-f3cb-11e8-8901-4f2de5d26dc3.png)

**Comment by BcRikko** [comment]
Thanks 🙇 

Since `title` uses `position: absolute`, I think that `overflow: scroll` is not enough. 🤔 
like below image.
![2018-11-29 17 50 42](https://user-images.githubusercontent.com/5305599/49210025-5d295500-f3ff-11e8-86ee-43759047ff96.png)

It's difficult to fix... 😭 
but I'll try my best. so please give me some time 🙏

**Comment by BcRikko** [comment]
resolved by #61
